filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /sources/manager-*/logs/alerts/alerts.json
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true

# --- Output to Wazuh Indexer (OpenSearch) over TLS (CA-only) ---
output.elasticsearch:
  hosts: ["https://wazuh-indexer.wazuh.lab:9200"]
  username: "admin"
  password: "admin"
  ssl:
    certificate_authorities: ["/usr/share/filebeat/certs/root-ca.pem"]
  index: "wazuh-alerts-4.x-%{+yyyy.MM.dd}"

# --- Disable ILM; use Wazuh template instead ---
setup.ilm.enabled: false

# --- Wazuh index template (JSON) ---
setup.template.name: "wazuh"
setup.template.pattern: "wazuh-*"
setup.template.overwrite: true
setup.template.json.enabled: true
setup.template.json.path: /etc/filebeat/wazuh-template.json
setup.template.json.name: "wazuh"

# --- Misc ---
logging.metrics.enabled: false

# Drop noisy host metadata (optional)
processors:
  - drop_fields:
      fields: ["host"]
      ignore_missing: true
